#!/bin/bash
# Regenerate web-optimized gallery images + manifest from the source photo library.
# Edit the SRC path or the PHOTOS list below to add/remove images, then re-run:
#   bash build-photos.sh
set -e

# Source folders searched (in order) for each photo's base filename.
SRC_DIRS=(
  "/Users/brysonloflin/Desktop/Summer pics/Edited_desktopdisplay.nosync"
  "/Users/brysonloflin/Pictures/Wallpapers/Current/ArchboldPhotos"
  "/Users/brysonloflin/Pictures/Wallpapers/Current"
)
SITE="/Users/brysonloflin/Claude/site"
FULL="$SITE/assets/photos"
THUMB="$SITE/assets/photos/thumbs"
mkdir -p "$FULL" "$THUMB"

# source_basename | out_slug | Common name | Scientific name | Location
PHOTOS=(
  "panama-060|caiman|Spectacled Caiman|Caiman crocodilus|Gamboa, Panamá"
  "Elegant_Trogon_1|trogon|Elegant Trogon|Trogon elegans|Chiricahua Mountains, Arizona"
  "Gila_Monster-1|gila-monster|Gila Monster|Heloderma suspectum|Arizona"
  "Mojave_Rattlesnake_1|mojave-rattlesnake|Mojave Rattlesnake|Crotalus scutulatus|Arizona"
  "Goulds_Turkey-1|goulds-turkey|Gould's Turkey|Meleagris gallopavo mexicana|Arizona"
  "Mexican_Jay_1|mexican-jay|Mexican Jay|Aphelocoma wollweberi|Arizona"
  "Acorn_Woodpecker-1|acorn-woodpecker|Acorn Woodpecker|Melanerpes formicivorus|Arizona"
  "Berylline_Hummingbird_1|berylline-hummingbird|Berylline Hummingbird|Saucerottia beryllina|Arizona"
  "Cliff_Chipmunk_1|cliff-chipmunk|Cliff Chipmunk|Neotamias dorsalis|Arizona"
  "Mexican_Fox_Squirrel_1|fox-squirrel|Mexican Fox Squirrel|Sciurus nayaritensis|Arizona"
  "Chiricahua_Leopard_Frog_2|leopard-frog|Chiricahua Leopard Frog|Lithobates chiricahuensis|Arizona"
  "Canyon_Treefrog_1|canyon-treefrog|Canyon Treefrog|Dryophytes arenicolor|Arizona"
  "Clarks_Spiny_Lizard_1|spiny-lizard|Clark's Spiny Lizard|Sceloporus clarkii|Arizona"
  "Chihuahuan_Spotted_Whiptail|chihuahuan-whiptail|Chihuahuan Spotted Whiptail|Aspidoscelis exsanguis|Arizona"
  "Desert_Grassland_Whiptail_1|grassland-whiptail|Desert Grassland Whiptail|Aspidoscelis uniparens|Arizona"
  "Chiricahua_Tarantula_1|tarantula|Chiricahua Tarantula|Aphonopelma sp.|Arizona"
  "Canyon_Towhee_1|canyon-towhee|Canyon Towhee|Melozone fusca|Arizona"
  "Sphinx_Moth_1|sphinx-moth|White-lined Sphinx Moth|Hyles lineata|Arizona"
  "panama-001|rainforest|Lowland tropical rainforest||Gamboa, Panamá"
  "Northern_Cardinal_1|cardinal|Northern Cardinal|Cardinalis cardinalis|North Carolina"
  "Yellow_Warbler_1|yellow-warbler|Yellow Warbler|Setophaga petechia|North Carolina"
  "White-Tailed_Deer_1|deer|White-tailed Deer|Odocoileus virginianus|North Carolina"
  # --- Florida (Archbold Biological Station / Lake Wales Ridge trip, Jan 2026) ---
  "BrysonsArchboldPics-58|scrub-jay|Florida Scrub-Jay|Aphelocoma coerulescens|Florida"
  "BrysonsArchboldPics-069|painted-bunting|Painted Bunting|Passerina ciris|Florida"
  "BrysonsArchboldPics-096|painted-bunting-2|Painted Bunting|Passerina ciris|Florida"
  "BrysonsArchboldPics-110|gopher-tortoise|Gopher Tortoise|Gopherus polyphemus|Florida"
  "BrysonsArchboldPics-108|gopher-tortoise-2|Gopher Tortoise|Gopherus polyphemus|Florida"
  "BrysonsArchboldPics-17|osprey|Osprey|Pandion haliaetus|Florida"
  "BrysonsArchboldPics-16|osprey-flight|Osprey|Pandion haliaetus|Florida"
  "BrysonsArchboldPics-41|american-alligator|American Alligator|Alligator mississippiensis|Florida"
  "BrysonsArchboldPics-093|white-ibis|White Ibis|Eudocimus albus|Florida"
  "BrysonsArchboldPics-49|double-crested-cormorant|Double-crested Cormorant|Nannopterum auritum|Florida"
  "BrysonsArchboldPics-090|great-egret|Great Egret|Ardea alba|Florida"
  "BrysonsArchboldPics-27|great-egret-2|Great Egret|Ardea alba|Florida"
  "BrysonsArchboldPics-52|anhinga|Anhinga|Anhinga anhinga|Florida"
  "BrysonsArchboldPics-101|red-cockaded-woodpecker|Red-cockaded Woodpecker|Dryobates borealis|Florida"
  "BrysonsArchboldPics-081|raccoon|Northern Raccoon|Procyon lotor|Florida"
  "BrysonsArchboldPics-083|raccoon-2|Northern Raccoon|Procyon lotor|Florida"
  "BrysonsArchboldPics-09|manatee|Florida Manatee|Trichechus manatus latirostris|Florida"
  "BrysonsArchboldPics-12|black-vulture|Black Vulture|Coragyps atratus|Florida"
  "BrysonsArchboldPics-63|scrub-lizard|Florida Scrub Lizard|Sceloporus woodi|Florida"
  "BrysonsArchboldPics-04|watersnake|Florida Watersnake|Nerodia fasciata|Florida"
)

MANIFEST="$SITE/assets/photos.json"
GALLERY="$SITE/assets/_gallery.html"   # generated partial, included by photography.qmd
echo "[" > "$MANIFEST"
echo "<!-- AUTO-GENERATED by build-photos.sh — do not edit by hand -->" > "$GALLERY"
echo '<div class="photo-grid">' >> "$GALLERY"
# Sort every photo by capture date (EXIF, read via mdls), most recent first, so
# the gallery leads with the newest work. Rows with no readable date sort last.
sorted_rows=$(
  for row in "${PHOTOS[@]}"; do
    IFS='|' read -r base slug common sci loc <<< "$row"
    in=""
    for d in "${SRC_DIRS[@]}"; do [ -f "$d/$base.jpg" ] && { in="$d/$base.jpg"; break; }; done
    if [ -z "$in" ]; then echo "  !! missing: $base.jpg (not in any SRC_DIR)" >&2; continue; fi
    dt=$(mdls -name kMDItemContentCreationDate -raw "$in" 2>/dev/null)
    if [ -z "$dt" ] || [ "$dt" = "(null)" ]; then dt="0000-00-00 00:00:00 +0000"; fi
    printf '%s\t%s\n' "$dt" "$row"
  done | sort -r
)

first=1
while IFS=$'\t' read -r dt row; do
  [ -z "$row" ] && continue
  IFS='|' read -r base slug common sci loc <<< "$row"
  in=""
  for d in "${SRC_DIRS[@]}"; do [ -f "$d/$base.jpg" ] && { in="$d/$base.jpg"; break; }; done
  [ -z "$in" ] && continue
  # portrait vs landscape aware: cap the LONG edge
  sips -Z 1600 --setProperty formatOptions 80 "$in" --out "$FULL/$slug.jpg" >/dev/null 2>&1
  sips -Z 800  --setProperty formatOptions 78 "$in" --out "$THUMB/$slug.jpg" >/dev/null 2>&1
  # orientation for layout
  h=$(sips -g pixelHeight "$in" 2>/dev/null | awk '/pixelHeight/{print $2}')
  w=$(sips -g pixelWidth  "$in" 2>/dev/null | awk '/pixelWidth/{print $2}')
  orient="landscape"; [ "$h" -gt "$w" ] && orient="portrait"
  # aspect ratio (width/height) lets the JS size each tile's grid row-span
  ar=$(awk -v w="$w" -v h="$h" 'BEGIN{ if (h+0>0) printf "%.4f", w/h; else printf "1.5" }')
  [ $first -eq 0 ] && echo "," >> "$MANIFEST"
  first=0
  printf '  {"slug":"%s","common":"%s","sci":"%s","loc":"%s","orient":"%s"}' \
    "$slug" "$common" "$sci" "$loc" "$orient" >> "$MANIFEST"
  # gallery figure (thumb links to full via data-full for the lightbox)
  cat >> "$GALLERY" <<HTML
  <figure class="photo photo--$orient" data-ar="$ar" data-full="assets/photos/$slug.jpg" data-common="$common" data-sci="$sci" data-loc="$loc" tabindex="0">
    <img loading="lazy" src="assets/photos/thumbs/$slug.jpg" alt="$common${sci:+ ($sci)}${loc:+, $loc}">
    <figcaption><span class="c-common">$common</span>${sci:+<span class="c-sci">$sci</span>}${loc:+<span class="c-loc">$loc</span>}</figcaption>
  </figure>
HTML
  echo "  ok: $slug ($orient) [$dt]"
done <<< "$sorted_rows"
echo "" >> "$MANIFEST"
echo "]" >> "$MANIFEST"
echo '</div>' >> "$GALLERY"
echo "Wrote $(grep -c '"slug"' "$MANIFEST") photos to manifest + gallery partial."
